events {
    worker_connections 1024;
}

http {
    upstream bytebank_app {
        server bytebank-app:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            proxy_pass http://bytebank_app/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /static/ {
            proxy_pass http://bytebank_app/static/;
        }

        location / {
            proxy_pass http://bytebank_app/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
